import type { Metadata } from "next";
import Image from "next/image";
import { Poppins } from "next/font/google";
import "./globals.css";

const poppins = Poppins({
    variable: "--font-poppins",
    subsets: ["latin"],
    weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" className={poppins.variable}>
            <body className="relative flex items-center justify-center min-h-screen w-screen overflow-hidden">
                <Image
                    src="/background_jemparingan.webp"
                    alt="Jemparingan background"
                    width={1000}
                    height={1000}
                    className="object-cover !aspect-9/16 !h-screen !w-auto"
                />
                <div className="absolute z-10 flex flex-col items-center justify-center h-full w-full">
                    {children}
                </div>
            </body>
        </html>
    );
}