import type { Metadata } from "next";
import Image from "next/image";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="relative flex items-center justify-center h-screen w-screen overflow-hidden">
        <Image
          src="/background_jemparingan.webp"
          alt="Jemparingan background"
          width={1000}
          height={1000}
          className="object-cover absolute !aspect-9/16 !h-screen !w-auto"
        />
          {/* <Footer /> */}
        <div className="absolute z-10 flex flex-col items-center justify-center h-full w-full">
          {children}
        </div>
      </body>
    </html>
  );
}

